### ISSUE TITLE
java 21 support

### ISSUE THREAD

**Issue by rutenkolk** [IGJoshua/coffi#8]
Hi there,

I wanted to ask if the java 21 support is ready for prime time, or if there is anything blocking the switch to java 21?

I made use of coffi in a project but it's a hassle to only have it work on java 19 and I would like to move to an LTS version of java, such as java 21.

If there is any specific work needed i'm willing to help out on finishing the work on the feature/jdk21-support branch.

**Comment by IGJoshua** [comment]
Hello! Thanks for the interest in coffi.

I really want to get JDK 21 and 22 support out the door. The basics of JDK 21 are functional, but upcalls are currently broken and cause JVM crashes, which is why I have not cut a release for it.

Since JDK 22 has come out and includes the full release of the foreign functions & memory API, I will likely directly move from the current support to JDK 22 once I have time to continue development.

Unfortunately for coffi's update schedule, work has been keeping me extremely busy, which on top of a cross-country move that I have coming up, I haven't been able to get back to working on JDK >21 support yet.

I'm hoping to have time to work on coffi again in August. If in the mean time I get any PRs associated with recent JDK support I will be happy to test and merge them.

**Comment by IGJoshua** [comment]
Fixed in #9 , will be in the next release.
